import Replicate from 'replicate';

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_KEY,
});

// Using Stable Diffusion 3 which produces high-quality clothing design images
const MODEL_VERSION = 'stability-ai/stable-diffusion-3:50adaf48d13e74a437c4f91d3751a7c11e352f83:8fda5fdf3367688b19e56887cd97069e0b0b2b79';

export async function generateImage(prompt) {
  try {
    if (!process.env.REPLICATE_API_KEY) {
      throw new Error('REPLICATE_API_KEY is not set');
    }

    console.log(`Generating image with prompt: "${prompt}"`);

    const output = await replicate.run(MODEL_VERSION, {
      input: {
        prompt: prompt,
        num_outputs: 1,
        height: 768,
        width: 768,
        num_inference_steps: 30,
        guidance_scale: 7.5,
        scheduler: 'DPMSolverMultistep',
      },
    });

    // Output is an array of image URLs
    if (!output || output.length === 0) {
      throw new Error('No image generated');
    }

    const imageUrl = output[0];

    // Fetch the image and convert to base64
    const response = await fetch(imageUrl);
    const buffer = await response.arrayBuffer();
    const base64Image = Buffer.from(buffer).toString('base64');
    const dataUrl = `data:image/jpeg;base64,${base64Image}`;

    return dataUrl;
  } catch (error) {
    console.error('Error generating image:', error.message);

    // Provide more helpful error messages
    if (error.message.includes('API key')) {
      throw new Error('Replicate API key is not configured. Contact administrator.');
    } else if (error.message.includes('rate')) {
      throw new Error('Rate limited by Replicate. Please try again in a moment.');
    } else if (error.message.includes('timeout')) {
      throw new Error('Image generation took too long. Please try again.');
    } else if (error.message.includes('NSFW')) {
      throw new Error('Prompt was flagged as inappropriate. Please try a different description.');
    }

    throw new Error(`Failed to generate image: ${error.message}`);
  }
}

// Alternative using FLUX model for faster generation (if primary fails)
export async function generateImageAlternative(prompt) {
  try {
    if (!process.env.REPLICATE_API_KEY) {
      throw new Error('REPLICATE_API_KEY is not set');
    }

    console.log(`Generating alternative image with FLUX model: "${prompt}"`);

    // Using FLUX model which is faster
    const output = await replicate.run('black-forest-labs/flux-pro', {
      prompt: prompt,
      image_size: 'square_hd',
      num_inference_steps: 25,
    });

    if (!output) {
      throw new Error('No image generated by alternative model');
    }

    // Output should be an image URL
    const imageUrl = typeof output === 'string' ? output : output[0];

    const response = await fetch(imageUrl);
    const buffer = await response.arrayBuffer();
    const base64Image = Buffer.from(buffer).toString('base64');
    const dataUrl = `data:image/jpeg;base64,${base64Image}`;

    return dataUrl;
  } catch (error) {
    console.error('Error generating alternative image:', error.message);
    throw new Error(`Failed to generate alternative image: ${error.message}`);
  }
}
